/* eslint-disable */
import axios from 'axios';
import cookie from 'js-cookie';

/**
 * Middleware for axios requests that adds relevant auth headers.
 */
axios.interceptors.request.use((config) => {
  // May additionally add a check to renew session token before continuing with request
  config.headers.Authorization = 'eyJraWQiOiJmUk1xT1J0SFNTcnk3RWNsYmtQbXlVK1wvZlNabjhWOElWWU5vY3A0K3Ricz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI4ZjVjOTZlOS0xZjJlLTQ3MjItOGRjOS04ODM5NWFmNTJlYTUiLCJldmVudF9pZCI6IjFlZGY0MmNkLTZiMjMtNDdjNC05NzIzLTYzOTc0M2Y0MWE3YyIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE2MDIyMTk2MDQsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTIuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0yX1cwRXRtZHg0cyIsImV4cCI6MTYwMjMwNjAwNCwiaWF0IjoxNjAyMjE5NjA1LCJqdGkiOiIzNDNlMzMwMC00MzgxLTQxY2EtYWFkZC01MzNhZmQxNjAwZjIiLCJjbGllbnRfaWQiOiI3dWQxcXJ1OGV1Mm8xdmh0Nm9vNnBodXRudSIsInVzZXJuYW1lIjoiOGY1Yzk2ZTktMWYyZS00NzIyLThkYzktODgzOTVhZjUyZWE1In0.euLFGXaJc8FVMXMq7uB0XoywbPmDZSnxZup1WWzhMKrO_89UUD5AgNAthQKuuvyTWJ4fx4lEQWfrf_xWt6yWHs9eaXSdApqvO4OozpActgjBqzoWfISObtlOFgt8vADFqjOoQn8OoQx9GJGQhcsNuTou9YTv_wJLZkQ4MrF3KOjVR1cjRZpmlYSMPRIon5qajyvF3Kymhb6riT-XoIlxHxLLjGbzRWAAkqQ0s68Pkbp2Mu1mpVG2G9jK5pli8uhrCWCTrHZ29dOnl8DQLbQwVNL-tex5r_K20WJZ4OMqZ2t7PN6uTM9coWpUmm4Xs7ZnYt9l-BOH3-mwOKddWQJibQ';
  return config;
  const access_token = cookie.get('access_token');
  if (access_token) {
    config.headers.Authorization = access_token;
  }
  return config;
});

export default axios;
