/* eslint-disable */
import axios from 'axios';
import cookie from 'js-cookie';

/**
 * Middleware for axios requests that adds relevant auth headers.
 */
axios.interceptors.request.use((config) => {
  // May additionally add a check to renew session token before continuing with request
   config.headers.Authorization = 'eyJraWQiOiJmUk1xT1J0SFNTcnk3RWNsYmtQbXlVK1wvZlNabjhWOElWWU5vY3A0K3Ricz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJiNWNkM2I4Yy04Njk5LTRkODgtYjgwNi00NTlkZmY2NjMxNzQiLCJldmVudF9pZCI6ImU1ZjljMTFhLTRmZGItNGMzZi1hOTU4LThlMjc5YjczNTBiYSIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE2MDQzNTczMTMsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTIuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0yX1cwRXRtZHg0cyIsImV4cCI6MTYwNDQ0MzcxMywiaWF0IjoxNjA0MzU3MzEzLCJqdGkiOiIxMDk1NTk1Yi0wZjNiLTQ3NjItOTk2YS03OGU1NDY2MmNmODEiLCJjbGllbnRfaWQiOiI3dWQxcXJ1OGV1Mm8xdmh0Nm9vNnBodXRudSIsInVzZXJuYW1lIjoiYjVjZDNiOGMtODY5OS00ZDg4LWI4MDYtNDU5ZGZmNjYzMTc0In0.VX3vcV8ASvhkynSq8e7y2DhS2UnLzB2s3UJ5wyU9xiRG0Jk2p3Cyf4T51yPtjdx6sMQCYSmEdi48QFfMGCS9-OHNJ50VmHnHfEp1Ldl0W6O24_vxDN7LbA_ia0gwKeHu1OWvcUhsMk0VElO7jiyQTUNvuEiP5GY0U6-x24v6YP_UaoCRiuU1wXILVMLKwYGFuvtMt6YuR5OPWZZY1cuTZhNN_8RuGxBTN9SuDGqCwgo0vYHnR-vzxlPx_r7gExBkEQ6fkEpB88QUKakdQ3c09mypB43-B6K5RRq0_xJ03tfn2gAhgwIBDIB-R0EffzW16VpqM-q5zaTDRhDQbnPC7w';
   return config;
  const access_token = cookie.get('access_token');
  if (access_token) {
    config.headers.Authorization = access_token;
  }
  return config;
});

export default axios;
