/* eslint-disable */
import axios from 'axios';
import cookie from 'js-cookie';

/**
 * Middleware for axios requests that adds relevant auth headers.
 */
axios.interceptors.request.use((config) => {
  // May additionally add a check to renew session token before continuing with request
  config.headers.Authorization = 'eyJraWQiOiJmUk1xT1J0SFNTcnk3RWNsYmtQbXlVK1wvZlNabjhWOElWWU5vY3A0K3Ricz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIwMzBlNmJmYi04MzQ4LTQzNzAtYjAzZi1mN2EwZWEyMzE2MDYiLCJjb2duaXRvOmdyb3VwcyI6WyJQbGF5ZXIiXSwiZXZlbnRfaWQiOiI0NjFhNDY2OS05MjNkLTQ4NTEtYTkyMy0yNWIxMjljNDYxMGUiLCJ0b2tlbl91c2UiOiJhY2Nlc3MiLCJzY29wZSI6ImF3cy5jb2duaXRvLnNpZ25pbi51c2VyLmFkbWluIiwiYXV0aF90aW1lIjoxNjAzOTI2NDExLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0yLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMl9XMEV0bWR4NHMiLCJleHAiOjE2MDQwMTI4MTEsImlhdCI6MTYwMzkyNjQxMSwianRpIjoiNDk1N2U4ZTUtZGQ5NS00NTgzLWIyYjMtNzIyZjY1MmU5NGNjIiwiY2xpZW50X2lkIjoiN3VkMXFydThldTJvMXZodDZvbzZwaHV0bnUiLCJ1c2VybmFtZSI6IjAzMGU2YmZiLTgzNDgtNDM3MC1iMDNmLWY3YTBlYTIzMTYwNiJ9.Lc5NUlaYtHzSuPS_34tcUd26Nkjy0h3Q5Xoccgu2G401vYPJc98i7IaguEy61YMsQcqovtujFxQ5_VNZBXm6NMv6SXqC4NnKOmaU86JVwdRHr2T6fAxNwLS8zz0h6iIPCRxHYAfyu8GYmaYUwskFAr79xj6PzTdMqTuEpAZBtW-GkAN6DvaliffXKSla_51YZDFK4MuO_CKaQ8hQWZJSlQya4AK__aTITePc571CYX1noN1URhs5fhbYG0xESvnksAkATZc4JQ6H59p0baZsalMNzn-HjIdMBRxx0W58EDtq1GQT5k5sTUScSTVmILPuvZndN4w74DdbjV226uvyLg';
  return config;
  const access_token = cookie.get('access_token');
  if (access_token) {
    config.headers.Authorization = access_token;
  }
  return config;
});

export default axios;
